server.port=8081

spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=profile_db;trustServerCertificate=true
spring.datasource.username=tuguldur
spring.datasource.password=Tuguldur0919

spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

soap.url=http://localhost:8080/ws/auth